# 3 NumPy

***
1. Создайте numpy.ndarray размерностью 3x4x2 и продемонстрируйте разные способы обращения по индексам из документации NumPy.
***

In [69]:
import numpy as np

arr = np.zeros((3, 4, 2))
arr.put((0, 0, 0), 1)
arr.put(6, 2)
print(arr)
print(arr.item(0))
print(arr.item(6))

[[[1. 0.]
  [0. 0.]
  [0. 0.]
  [2. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
1.0
2.0


 ***
2. Попробуйте сравнить по производительности numpy.array и list, выполняя какую-то стандартную операцию с каждым из типов много раз. 
***

In [91]:
import numpy as np
import time

array = np.random.randint(100, size=(300, 300))
list = []
for x in range(1, 90000, 1):
    list.append(x)
    
#np.array
start_time = time.time()
for x in range(1, 10000, 1):
    tmp = np.sum(array)
print("%s seconds" % (time.time() - start_time))
print(tmp)
#list
start_time = time.time()
for x in range(1, 10000, 1):
    tmp = sum(list)
print("%s seconds" % (time.time() - start_time))
print(tmp)

0.4042980670928955 seconds
4462731
4.421251058578491 seconds
4049955000


***
3. Изучите numpy.linspace(), напишите свою реализацию аналогичной функции с помощью list comprehension, дающий тот же результат, только в виде list, а не numpy.ndarray. Сравните по производительности два варианта на достаточно больших массивах.
***

In [106]:
#np.array
start_time = time.time()
array = np.linspace(1, 100000, num=1000000)
print("%s seconds" % (time.time() - start_time))

def linspace(start, end,  num):
    list = []
    for x in range(start, end, num):
        list.append(x)
    return list

#list
start_time = time.time()
list = linspace(1, 100000, 1000000)
print("%s seconds" % (time.time() - start_time))

0.0017442703247070312 seconds
9.512901306152344e-05 seconds
